[package]
name = "rend"
version = "0.1.0"
authors = ["Wesley Aptekar-Cassels <W.Aptekar@gmail.com>"]

[dependencies]

nalgebra = "0.12.3"

piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.43.0"
